Replace ad-hoc command-not-found generation scripts with nix-index
NixOS/nixos-channel-scripts pull request #62
Opened 2022-11-12 14:17 UTC by K900

This is much, MUCH faster than the existing solution, especially on large channels. It can be made even faster if we actually reuse anything whatsoever, but this is a massive improvement in itself.

TODO:
- [ ] also generate the debuginfo JSON

2022-11-12 17:44 UTC, K900 commented
Related nix-index PR: https://github.com/bennofs/nix-index/pull/192

2023-01-10 14:43 UTC, SuperSandro2000 commented on flake.nix
> +              --prefix PATH : ${wget}/bin:${git}/bin:${final.nix}/bin:${gnutar}/bin:${xz}/bin:${rsync}/bin:${openssh}/bin:${nix-index'}/bin:${nixos-channel-native-programs}/bin:$out/bin
This should use lib.makeBinPath

2023-01-12 18:04 UTC, K900 commented on flake.nix
> +              --prefix PATH : ${wget}/bin:${git}/bin:${final.nix}/bin:${gnutar}/bin:${xz}/bin:${rsync}/bin:${openssh}/bin:${nix-index'}/bin:${nixos-channel-native-programs}/bin:$out/bin
Fixed.

2023-01-26 02:31 UTC, grahamc requested changes
I think I figured out the issue we were seeing yesterday. If you can get an updated revision up, we can try again my morning!

2023-01-26 02:31 UTC, grahamc commented on index-debuginfo.cc
> +        if (binaryCache->fileExists(build_id)) return;
member was renamed to build_id, and key was renamed to url

2023-01-26 02:31 UTC, grahamc commented on index-debuginfo.cc
> -                std::string key = "debuginfo/" + buildId;
the `debuginfo/` prefix is important here, and losing this prefix in the key we upsert to s3 is (I believe) the issue we're seeing here

2023-01-26 02:31 UTC, grahamc commented on index-debuginfo.cc
> -                std::string key = "debuginfo/" + buildId;
is the `url` column the URL to the nar?

2023-01-26 02:32 UTC, grahamc commented on index-debuginfo.cc
> +        if (binaryCache->fileExists(build_id)) return;
(and key was `debuginfo/<buildid>`)

2023-01-26 02:35 UTC, grahamc commented on index-debuginfo.cc
> +    auto doFile = [&](std::string build_id, std::string url, std::string filename) {
In general, I'm a little bit spooked by the renaming of the variables in this function. I think if this function hadn't been altered it would have been more clear to me that something fishy was going on around the debuginfo prefix. It is probably fine, though.

2023-01-26 13:32 UTC, grahamc commented on index-debuginfo.cc
> +        std::string key = "debuginfo/" + buildId;
```suggestion
        std::string key = "debuginfo/" + build_id;
```

2023-01-26 13:45 UTC, edolstra commented
I think we should just get rid of `command-not-found` entirely, since it's not compatible with flakes. (Flakes are fetched directly from GitHub so there is no opportunity to add a SQLite database to the distribution.)

I'm also not really in favor of making our release process depend on an external project that we have no control over.

2023-01-26 13:47 UTC, K900 commented
I'm all for it, but I'd rather not make the call here. It should probably be brought up as an issue on the nixpkgs repo so we can get some more feedback.

2023-01-26 13:51 UTC, K900 commented
That said, I do think this is a good stopgap until a decision is made on removing legacy c-n-f, as channel updates take double digit hours with the current implementation.

2023-01-30 14:08 UTC, merged

2023-02-01 10:51 UTC, SuperSandro2000 commented
> I think we should just get rid of `command-not-found` entirely, since it's not compatible with flakes.

We need some c-n-f implementation. Luckily binary locations do not change that often so we could get away with just providing a database for each release which are fetched separately or updated in nixpkgs.
Removing it entirely is not an option for me.

2023-02-01 10:52 UTC, K900 commented
Maybe we can adopt nix-index as an official project then, if @bennofs is interested.