mirror-nixos-branch: omit minimal ISOs from small channels
NixOS/nixos-channel-scripts pull request #74
Opened 2024-08-30 16:48 UTC by emilazy

See https://github.com/NixOS/nixpkgs/pull/338433.

I’m not very good at Perl and I don’t know how to test these scripts, so I’d appreciate some scrutiny here.

2024-09-01 14:39 UTC, vcunat requested changes
I believe this is needed to trigger e.g. on `nixos-23.11-small`.  Otherwise it looks good to me.

2024-09-01 14:39 UTC, vcunat commented on mirror-nixos-branch.pl
> +            $channelName =~ /nixos-2([0123]|4\.05)-small/) {
```suggestion
            $channelName =~ /nixos-2([0123]\...|4\.05)-small/) {
```

2024-09-01 14:59 UTC, emilazy commented on mirror-nixos-branch.pl
> +            $channelName =~ /nixos-2([0123]|4\.05)-small/) {
Ah, of course; I only added the `-small` after. Fixed.

2024-09-01 15:12 UTC, vcunat approved these changes

2024-09-05 12:19 UTC, emilazy commented
@vcunat https://github.com/NixOS/nixpkgs/pull/338433 has three 👍s now; do you think that’s adequate approval or would you like to see more response here before merge? (I linked it in the Matrix contributors room a few days ago to no response other than those; not sure how I could get more reactions from people who would particularly care.)

2024-09-06 07:50 UTC, merged